services:
  - type: web
    name: clinicms
    runtime: python
    runtimeVersion: 3.12
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput
    startCommand: gunicorn clinicms.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1"
